branchName: '${issue.number}'
branches:
  - label: '🚀 feature'
    prefix: 'feature/'
  - label: '🔨 refactor'
    prefix: 'feature/'
  - label: '🐛 bug'
    prefix: 'fix/'
  - label: '*'
    prefix: 'feature/'
commentMessage: 'Branch ${branchName} 로 생성되었어요 🎉'
autoCloseIssue: true
autoLinkIssue: true
openDraftPR: true
